apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: syfctrfbr-go 
  janus-idp.io/tekton: syfctrfbr-go
  backstage.io/kubernetes-id: syfctrfbr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: syfctrfbr-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml